---
title: "Plataforma Mobills - Análise de Despesas Pessoais"
subtitle: "https://github.com/erickfis"
author: "Erick Gomes Anastácio"
date: "`r format(Sys.time(), '%Y %B, %d')`"


output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    toc: true
    self_contained: no

---


```{r knit-rules, echo=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, include = TRUE, 
               warning = FALSE, autodep = TRUE, options(scipen=999))

source(here::here("engine", "processamento.R"))


```
# Objetivo

Análise do orçamento familiar, com base nos dados obtidos pela plataforma mobils.

https://web.mobills.com.br


*ESTE RELATÓRIO ESTÁ EM CONSTANTE CONSTRUÇÃO* 


```{r child = 'engine/outliers.Rmd'}
```        

```{r child = 'engine/maiores.Rmd'}
```        

```{r child = 'engine/custo-mes.Rmd'}
```  
<br>

# Principais tipos de despesas

```{r child = 'engine/alimentacao.Rmd'}
```        

```{r child = 'engine/moradia.Rmd'}
```        


```{r child = 'engine/pagamentos.Rmd'}
```        

```{r child = 'engine/corolla.Rmd'}
```        

```{r child = 'engine/pet.Rmd'}
```   

```{r child = 'engine/intros.Rmd'}
```        


```{r child = 'engine/conclusao.Rmd'}
```        

