---
title: "Plataforma Mobills - análise de despesas"
author: "erickfis"
date: "`r format(Sys.time(), '%Y %B, %d')`"


output:
   md_document:
         toc: true


# output:
#         html_document:
#                 toc: true
#                 toc_depth: 3
#                 number_sections: true
#                 self_contained: yes
#                 keep_md: false
#                 fig_crop: false
#                 classoption: landscape


# output:
#   pdf_document:
#         toc: true
#         toc_depth: 3
#         number_sections: true
#         keep_tex: true
---


```{r knit-rules, echo=FALSE}
library(knitr)

opts_chunk$set(echo = FALSE, message = FALSE, include = TRUE, 
               warning = FALSE, autodep = TRUE, options(scipen=999),
               fig.pos = 'H')

```




```{r child = 'intros.Rmd'}
```

```{r child = 'processamento.Rmd'}
```        

# Principais tipos de despesas

```{r child = 'alimentacao.Rmd'}
```        

```{r child = 'pagamentos.Rmd'}
```        

```{r child = 'corolla.Rmd'}
```        


```{r child = 'conclusao.Rmd'}
```        

