
## Análise por tipo de despesa: Alimentação

Vejamos como este tipo de despesa se comporta ao longo dos anos:


```{r alimentacao}
#devidos subsets

totais.alim <- totais[totais$tipo=="alimentação",]

medias.alim <- totais.alim %>% group_by(ano) %>%
        summarise(media = mean(total.raw))

medias.alim$media <- round(medias.alim$media, 2)

plt.alim <- ggplot(totais.alim, aes(x=mes, y=total.raw, group=ano, colour=ano,
                text = paste(ano, "-", mes, 
                             "<br>", total)))
                                 
plt.alim <- plt.alim +  geom_line() + 
                geom_point(size=1, alpha=0.5) +
                geom_hline(data = medias.alim, 
                           aes(yintercept = media, colour = ano,
                                 text=paste(real(media))),
                           linetype=2) +
                # geom_label(data = medias.alim, vjust = -0.2, hjust = 1,
                #           aes(12, y = media,label=media)) +
                labs(title="Gastos com alimentação", y="Total (R$)", x="Mês") +
                theme(plot.title = element_text(hjust = 0.5)) 

ggplotly(plt.alim, tooltip = "text")

```

Observa-se problemas em

- abril, junho e julho
- aumento consecutivo da média
- as compras maiores são feitas a cada 2 meses

Vamos analisar na tabela de dados os principais registros:

```{r tabela-alim}
sub <- which(dadosFil$mes %in% c("Abr", "Jun", "Jul") & 
                     dadosFil$tipo=="alimentação" & dadosFil$valor.raw > 50) 



dadosFil[sub, c(2,3,6,7)]  %>% 
        datatable(options = list(pageLength = 6), 
                  caption = "Picos de gastos com alimentação",
                  rownames = FALSE, filter = "top"
                  )
# rank <- order(dados.sel$valor.raw, decreasing = TRUE)

# kable(dados.sel[,c(1,6,8)], caption = "Gastos em Abril")

###

# sub <- which(dadosFil$mes %in% c("Jun") & 
#                      dadosFil$tipo=="alimentação" & dadosFil$valor.raw > 50) 
# 
# dados.sel <- dadosFil[sub,]
# #rank <- order(dados.sel$valor.raw, decreasing = TRUE)
# 
# kable(dados.sel[,c(1,6,8)], caption = "Gastos em Junho")
# 
# ###
# 
# sub <- which(dadosFil$mes %in% c("Jul") & 
#                      dadosFil$tipo=="alimentação" & dadosFil$valor.raw > 50) 
# 
# dados.sel <- dadosFil[sub,]
# # rank <- order(dados.sel$valor.raw, decreasing = TRUE)
# 
# kable(dados.sel[,c(1,6,8)], caption = "Gastos em Junho")


```




