
# Maiores Despesas por tipo

Na tabela abaixo temos um ranking dos maiores tipos de despesa na média de todos os anos:

```{r maiores.despesas, cache=TRUE}

maiores <- totais %>% group_by(tipo, ano) %>% 
        summarise(media.anual = round(mean(total.raw),2),
                  sd.anual=round(sd(total.raw), 2)) %>%
        mutate(media.geral = round(mean(media.anual),2),
               sd.geral=round(sd(media.anual), 2)) %>%
        arrange(desc(media.geral), ano, tipo) 

maiores <- subset(maiores, media.geral > 200)

# maiores$rank <- rank(maiores$media.geral)
# 
# maiores$r2 <- ave(maiores$media.geral, FUN = function(x) rank(-x, ties.method = "min"))

```

```{r maiores.despesas.table, cache=TRUE}

maiores.df.plot <-  maiores %>% group_by(tipo) %>% 
        summarise(media = round(mean(media.anual),2)) %>%
        arrange(desc(media)) %>%
        # mutate(rank = 1:length(media))
        mutate(rank = rank(media))

maiores.df.plot$tipo <- factor(maiores.df.plot$tipo,
                levels = maiores.df.plot$tipo[order(maiores.df.plot$rank,
                                                decreasing = FALSE)])

maiores$tipo <- factor(maiores$tipo, levels = maiores.df.plot$tipo)

maiores$ano <- factor(maiores$ano,
                levels = c(2017, 2016,2015))


dados <- maiores.df.plot[, c(3,1:2)]
dados$media <- real(dados$media)
kable(dados, caption = "Os maiores tipos de despesas")
```


```{r maiores-plot, cache=TRUE}

real <- dollar_format(prefix = "R$ ")

colourCount = length(unique(maiores.df.plot$tipo))
getPalette = colorRampPalette(brewer.pal(colourCount, "Set1"))

# maiores.plt <- ggplot(maiores.df.plot, aes(tipo, media, fill=tipo))
# 
# maiores.plt <- maiores.plt + geom_bar(stat="identity") +
#         labs(title=" Média das maiores despesas, por tipo", 
#              y="", x="") + 
#         geom_text(aes(label=tipo),
#                 vjust=.5, hjust=1.1, colour="white") +
#         scale_y_continuous(labels = real) +
#         scale_colour_manual(values = getPalette(colourCount))+ 
#         theme(legend.position="none") +    
#         theme(legend.title=element_blank()) +
#         theme(axis.text.y = element_blank()) + 
#         theme(axis.ticks.y = element_blank()) + 
#         theme(plot.title = element_text(hjust = 0.5)) +
#         coord_flip()
# 
# maiores.plt


maiores.plt <- ggplot(maiores.df.plot, aes(tipo, media, fill=tipo))

maiores.plt <- maiores.plt + geom_bar(stat="identity") +
        labs(title=" Média das maiores despesas, por tipo",
             y="", x="") +
        geom_text(aes(label=tipo),
                vjust=.5, hjust=1.1, colour="white") +
        scale_y_continuous(labels = real) +
        scale_colour_manual(values = getPalette(colourCount))+
        theme(legend.position="none") +
        theme(legend.title=element_blank()) +
        theme(axis.text.y = element_blank()) +
        theme(axis.ticks.y = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5)) +
        coord_flip()

maiores.plt
ax <- list(
  # title = ""
  # zeroline = FALSE,
  # showline = FALSE,
  showticklabels = FALSE
  # showgrid = FALSE
)

p <- plot_ly(maiores.df.plot, x = ~media, y = ~tipo, type = 'bar',
             orientation = 'h', color=~tipo, hoverinfo = "text",
             text = ~paste(tipo, ":", real(media))) %>%
  layout(yaxis = ax)




```



```{r maiores-plot-2, cache=TRUE}

real <- dollar_format(prefix = "R$ ")

colourCount = length(unique(maiores$tipo))
getPalette = colorRampPalette(brewer.pal(colourCount, "Set1"))

maiores.plt <- ggplot(maiores, aes(tipo, media.anual, 
                                   fill=ano))

maiores.plt <- maiores.plt + 
        geom_bar(stat="identity", position = position_dodge()) +
        facet_grid(tipo~., scales = "free", space = "free") +
        theme(strip.text.y = element_text(angle = 0)) +                
        labs(title=" Média das maiores despesas, por ano", 
             y="", x="") + 
        # geom_text(aes(label=tipo),
        #         vjust=.5, hjust=1.1, colour="white") +
        scale_y_continuous(labels = real) +
        scale_colour_manual(values = getPalette(colourCount))+ 
        theme(legend.position="bottom") +    
        theme(legend.title=element_blank()) +
        theme(axis.text.y = element_blank()) + 
        theme(axis.ticks.y = element_blank()) + 
        # theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 

        theme(plot.title = element_text(hjust = 0.5)) +
        coord_flip()

maiores.plt
# maiores.plt + coord_flip()
```



# Maiores Variações 


Pode ser interessante analisar as categorias que apresentam as maiores variações ao longo dos anos


Na tabela abaixo temos um ranking dos tipos de despesas que apresentaram os maiores desvios padrões da média:

```{r variacoes-plot, cache=TRUE}

m.variacoes <-  maiores %>% group_by(tipo) %>% 
        summarise(sd = round(sd(media.anual),2)) %>%
        arrange(desc(sd)) %>%
        mutate(rank = 1:length(sd))

m.variacoes <- subset(m.variacoes, sd > 50)

dados <- m.variacoes[, c(3,1:2)]
dados$sd <- real(dados$sd)

kable(dados, caption = "Maiores variações ao longo dos anos")

m.variacoes$tipo <- factor(m.variacoes$tipo,
                levels = m.variacoes$tipo[order(m.variacoes$rank, 
                                                decreasing = TRUE)])


colourCount = length(unique(m.variacoes$tipo))
getPalette = colorRampPalette(brewer.pal(colourCount, "Set1"))

variacoes.plt <- ggplot(m.variacoes, aes(tipo, sd, fill=tipo))

variacoes.plt <- variacoes.plt + geom_bar(stat="identity") +

        geom_text(aes(label=tipo),
                vjust=.5, hjust=1.1, colour="white") +
        
        labs(title="Maiores variações por tipos de despesas", 
             y="Desvio Padrão", x="") + 
                
        theme(legend.position="none") +        
        scale_colour_manual(values = getPalette(colourCount))+   
        scale_y_continuous(labels = real) +
        theme(legend.title=element_blank()) +
        theme(axis.text.y = element_blank()) + 
        theme(axis.ticks.y = element_blank()) + 
        theme(plot.title = element_text(hjust = 0.5)) +
        coord_flip()

variacoes.plt


```



