


## Análise por tipo de despesa: Pagamentos

```{r plot-pagamentos}
totais.pag <- totais[totais$tipo=="pagamentos",]
medias.pag <- totais.pag %>% group_by(ano) %>%
        summarise(media = mean(total.raw))

medias.pag$media <- round(medias.pag$media, 2)


plt.pag <- ggplot(totais.pag, aes(x=mes, y=total.raw, group=ano, colour=ano,
                text = paste(ano, "-", mes, 
                             "<br>", total)))                                  

plt.pag <- plt.pag +  geom_line() +
                geom_point(size=1, alpha=0.5) +
                geom_hline(data = medias.pag, 
                           aes(yintercept = media, colour = ano,
                                 text=paste(real(media))),
                           linetype=2) +
                # geom_label(data = medias.pag, vjust = -0.2, hjust = 1,
                #           aes(12, y = media,label=media)) +
                # 
                labs(title="Gastos com pagamentos diversos", 
                     y="Total (R$)", x="Mês") +
                theme(plot.title = element_text(hjust = 0.5))

ggplotly(plt.pag, tooltip = "text")
```

Observa-se alguns picos, vamos analisar a tabela de dados, em especial para valores acima de R$250,00:


```{r tabela-pag}

sub <- which(dadosFil$tipo=="pagamentos" & 
                     dadosFil$mes %in% c("Fev", "Abr", "Ago", "Out"))


dadosFil[sub, c(2,3,6,7)]  %>% 
        datatable(options = list(pageLength = 6), 
                  caption = "Picos de gastos com pagamentos",
                  rownames = FALSE, filter = "top"
        )


```




